### ISSUE TITLE
Unable to resolve actions. Repository not found.

### ISSUE THREAD

**Issue by paalr** [Pwd9000-ML/terraform-azurerm-plan#11]
Hi, I tried to follow your guide on [dev.to](https://dev.to/pwd9000/automated-terraform-tests-for-azure-using-github-actions-4349) but get the error `Unable to resolve actions. Repository not found: tfsec/tfsec-sarif-action`. I think that is caused by this repo, but I can see that the action is working fine in your repo, i.e. [terraform-azurerm-dynamic-subnets](https://github.com/Pwd9000-ML/terraform-azurerm-dynamic-subnets/actions/runs/3173507948/jobs/5169201185#step:2:1 ) which is throwing me a bit of. Any suggestions or pointers?

**Comment by Pwd9000-ML** [comment]
@paalr Is this still an issue?
Can you send me a link to your workflow that is failing or paste some more information here?

**Comment by paalr** [comment]
@Pwd9000-ML Yes, just tried it now in "debug mode" and still gets an issue. Our repo is private, but here is a snippet from the log:

```shell
[42]##[debug]Download action repository 'Pwd9000-ML/terraform-azurerm-plan@v1.2.4' (SHA:c6987fc40f2110e0aa9cc71979e0fbd78d7f3a1a)
[43]##[debug]Download 'https://api.github.com/repos/Pwd9000-ML/terraform-azurerm-plan/tarball/c6987fc40f2110e0aa9cc71979e0fbd78d7f3a1a' to '/home/runner/work/_actions/_temp_5c11a89b-83c6-4647-b903-533f5c393cf9/d536c311-930d-4e37-bab5-528437ef75c5.tar.gz'
[44]##[debug]Unwrap 'Pwd9000-ML-terraform-azurerm-plan-c6987fc' to '/home/runner/work/_actions/Pwd9000-ML/terraform-azurerm-plan/v1.2.4'
[45]##[debug]Archive '/home/runner/work/_actions/_temp_5c11a89b-83c6-4647-b903-533f5c393cf9/d536c311-930d-4e37-bab5-528437ef75c5.tar.gz' has been unzipped into '/home/runner/work/_actions/Pwd9000-ML/terraform-azurerm-plan/v1.2.4'.
[46]Download action repository 'Pwd9000-ML/terraform-azurerm-apply@v1.2.4' (SHA:32f27dea1c3dc99e39c1b971304ec9298d5132ed)
[47]##[debug]Download 'https://api.github.com/repos/Pwd9000-ML/terraform-azurerm-apply/tarball/32f27dea1c3dc99e39c1b971304ec9298d5132ed' to '/home/runner/work/_actions/_temp_f25ac786-cd02-404b-8451-c1daabf99250/d8c08323-954b-4474-98ff-6c4f0f58e328.tar.gz'
[48]##[debug]Unwrap 'Pwd9000-ML-terraform-azurerm-apply-32f27de' to '/home/runner/work/_actions/Pwd9000-ML/terraform-azurerm-apply/v1.2.4'
[49]##[debug]Archive '/home/runner/work/_actions/_temp_f25ac786-cd02-404b-8451-c1daabf99250/d8c08323-954b-4474-98ff-6c4f0f58e328.tar.gz' has been unzipped into '/home/runner/work/_actions/Pwd9000-ML/terraform-azurerm-apply/v1.2.4'.
[50]##[debug]Action 'Pwd9000-ML/terraform-azurerm-plan@v1.2.4' already downloaded at '/home/runner/work/_actions/Pwd9000-ML/terraform-azurerm-plan/v1.2.4'.
[51]##[debug]Action 'Pwd9000-ML/terraform-azurerm-apply@v1.2.4' already downloaded at '/home/runner/work/_actions/Pwd9000-ML/terraform-azurerm-apply/v1.2.4'.
[52]##[debug]action.yml for action: '/home/runner/work/_actions/Pwd9000-ML/terraform-azurerm-plan/v1.2.4/action.yml'.
[53]Getting action download info
[54]Error: Unable to resolve actions. Repository not found: tfsec/tfsec-sarif-action.
[55]##[debug]GitHub.DistributedTask.WebApi.UnresolvableActionDownloadInfoException: Unable to resolve actions. Repository not found: tfsec/tfsec-sarif-action.
```

**Comment by Pwd9000-ML** [comment]
Thank you @paalr 
Can you confirm you're using GitHub enterprise with the private repo?

If not you'd would need to set the parameter on the workflow to use TFEC to false

    enable_TFSEC: false

If using a private repository, GitHub enterprise is needed when enabling TFSEC. However if a public repository is used, code analysis is included and TFSEC can be enabled on public repositories without the need for a GitHub enterprise account.

**Comment by paalr** [comment]
@Pwd9000-ML I have to correct myself, it is an internal repo, not private. I have confirmed that we have Gihub Enterprise. I guess I need to use `enable_TFSEC: false` then?

**Comment by paalr** [comment]
@Pwd9000-ML I have done some more testing and it seems that the parameter `enable_TFSEC: false` doesn't have any effect on an internal GitHub repo, I think it stops before the parameter is evaluated. To me it seems like the GitHub action tries to resolve and download all dependencies during initialisation, including `tfsec/tfsec-sarif-action`, regardless of the parameter `enable_TFSEC: false`. 

This is my GitHub action test:

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Dev TF Plan
        uses: Pwd9000-ML/terraform-azurerm-plan@v1.2.4
        with:
          plan_mode: deploy
          tf_version: latest
          tf_vars_file: testing.tfvars
          tf_key: tf-tests
          enable_TFSEC: false
          az_resource_group: BackendRG
          az_storage_acc: tfstate
          az_container_name: backend-remote-state
          arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
          arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
          arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
```
And this is the result:
```shell
Current runner version: '2.298.2'
Operating System
Runner Image
Runner Image Provisioner
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v3.1.0' (SHA:93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8)
Download action repository 'Pwd9000-ML/terraform-azurerm-plan@v1.2.4' (SHA:c6987fc40f2110e0aa9cc71979e0fbd78d7f3a1a)
Getting action download info
Error: Unable to resolve actions. Repository not found: tfsec/tfsec-sarif-action.
```
